### ISSUE TITLE
No data output from jetiexbus after enabling ms5611

### ISSUE THREAD

**Issue by ahfynjj** [dgatf/msrc#78]
I am planning to make a 2 in 1 sensor, GPS and MS5611 altimeter, and tried to use the new GPS module, and the test was successful, but after compiling the code with MS5611, it does not work. I also tested the MS5611 separately and it doesn't work either. Here is my config.h file

```
#ifndef CONFIG_H
#define CONFIG_H
#include "constants.h"

/* Receiver protocol */
#define RX_PROTOCOL RX_JETIEX

/* Sensors */
#define CONFIG_ESC_PROTOCOL PROTOCOL_NONE
#define CONFIG_GPS true
#define GPS_BAUD_RATE 115200 
#define CONFIG_VOLTAGE1 false 
#define CONFIG_VOLTAGE2 false 
#define CONFIG_NTC1 false 
#define CONFIG_NTC2 false 
#define CONFIG_CURRENT false 
#define CONFIG_AIRSPEED false 
#define CONFIG_I2C1_TYPE I2C_MS5611 
#define CONFIG_I2C1_ADDRESS 0x77

/* Refresh rate in 0.1s (1 = 100ms) */
#define CONFIG_REFRESH_RPM 1
#define CONFIG_REFRESH_VOLT 1
#define CONFIG_REFRESH_CURR 1
#define CONFIG_REFRESH_TEMP 1
#define CONFIG_REFRESH_GPS 1

/* Averaging elements (1 = no averaging) */
#define CONFIG_AVERAGING_ELEMENTS_RPM 1
#define CONFIG_AVERAGING_ELEMENTS_VOLT 1
#define CONFIG_AVERAGING_ELEMENTS_CURR 1
#define CONFIG_AVERAGING_ELEMENTS_TEMP 1
#define CONFIG_AVERAGING_ELEMENTS_DEF 1

/* Analog multipliers */
#define VOLTAGE1_MULTIPLIER 1
#define VOLTAGE2_MULTIPLIER 1
#define CURRENT_MULTIPLIER 1

/* RPM multipliers (optional, this may be done in transmitter*/
#define RPM_PAIR_OF_POLES 1
#define RPM_PINION_TEETH 1
#define RPM_MAIN_TEETH 1

/* BMP filter. Higher filter = lower noise: 1 - low, 2 - medium, 3 - high */
#define BMP280_FILTER 3

/* Pwm out */
#define CONFIG_PWMOUT false
#define PWMOUT_DUTY 0.5 // 0.5 = 50%

/* Only smartport and opentx */
#define SENSOR_ID 10 // Sensor Id
#define DATA_ID 0x5000 // DataId (sensor type)
//#define ESC_SIGNATURE // HW V4 signature (only smartport). This outputs esc signature and raw current to sensors 5100, 5101 and 5102
//#define CONFIG_LUA

/* XBus */
//#define XBUS_CLOCK_STRECH_SWITCH

/* Jeti Ex */
#define JETI_GPS_SPEED_UNITS_KMH

/* Use library I2C_T3 for Teensy LC/3.X */
#define I2C_T3_TEENSY

/* Add init delay for FlyFun ESC. Uncomment if the ESC doesn't arm */
//#define ESC_INIT_DELAY 10000

/* HW V4/V5 parameters */
#define CURRENT_THRESHOLD 25
#define ESCHW4_DIVISOR 11
#define ESCHW4_AMPGAIN 0
#define ESCHW4_CURRENT_MAX 0

/* Force eeprom write */
//#define FORCE_EEPROM_WRITE // Uncomment to force write eeprom as defined in config.h. Useful when using lua and eeprom is messed up. Reflash againg with line commented or config will be reset at power up

/* Debug
   Disconnect Vcc from the RC model to the Arduino
   Do not connect at the same time Vcc from the model and usb (TTL)
   Telemetry may not work properly in debug mode
   Connect arduino Rx to TTL Tx for flashing, then if applicabe connect arduino Rx to esc or gps
*/

//#define DEBUG
//#define DEBUG_PACKET
//#define DEBUG_SBUS_MS
//#define DEBUG_EEPROM_WRITE
//#define DEBUG_EEPROM_READ

//#define DEBUG_HW3
//#define DEBUG_HW4
//#define DEBUG_ESC_KONTRONIK
//#define DEBUG_APDF
//#define DEBUG_APDHV
//#define DEBUG_GPS
//#define DEBUG_PWM
//#define DEBUG_CASTLE
//#define DEBUG_CASTLE_RX

//#define SIM_RX
//#define SIM_SENSORS
//#define SIM_LUA_SEND
//#define SIM_LUA_RECEIVE

#endif
```

**Comment by dgatf** [comment]
Which board are you using?

**Comment by dgatf** [comment]
Have you added pull up resistors to SDA and SCL?

**Comment by dgatf** [comment]
Have you tested the ms5611 with a separate library to test if it works?

**Comment by dgatf** [comment]
This is issue is due to no memory available. The maximum number of sensors for Jeti with ATmega328 (2k ram) is 10 sensors

I've added a parameter in jetiex.h, JETIEX_LOW_MEMORY. It is disabled by default. You need to enable it (uncomment it). If this parameter is enabled, some sensors with less important telemetry values are not created.

It disables the following sensors:

- GPS. Date, time and hdop
- Barometer (BMP280 & MS5611). Air temperature

**Comment by dgatf** [comment]
>  I also tested the MS5611 separately and it doesn't work either

If you disable the GPS, then you need to connect Jeti to Rx & Tx pins instead

**Comment by ahfynjj** [comment]
Following your instructions, I disabled some sensors in the code and it worked successfully. thank you very much.
But I observed that the reading of MS5611 was abnormal, and the same thing happened with another brand new one
![123](https://user-images.githubusercontent.com/5051629/158920164-0b721274-2317-44c6-a2a5-3a0ddad46607.jpg)
![456](https://user-images.githubusercontent.com/5051629/158920167-2b88dfab-5495-4b70-af91-379a266e99ba.jpg)
.

**Comment by dgatf** [comment]
Please enable DEBUG_MS5611 in config.h, connect arduino Tx to programmer Rx and arduino GND to programmer GND. With a serial monitor at 9600, post the output

**Comment by ahfynjj** [comment]
After many attempts I got correct data output at 250000 baud, not gibberish at 9600 baud. As shown below
![33](https://user-images.githubusercontent.com/5051629/158930746-049bbd14-8996-4042-b7e8-793d0bc3bf53.jpg)

At the same time, I conducted the serial port test of arduino Libraries, the data is as follows
![2](https://user-images.githubusercontent.com/5051629/158930753-500c2cde-72dc-4050-8d5f-3236b85d2a37.jpg)

**Comment by dgatf** [comment]
Sorry, my bad. There was an error reading the PROM parameters from MS5611. Fixed with 57b3a8dcdd4de028674db9bdd88a07f961aa2330

**Comment by ahfynjj** [comment]
The problem is stil
![微信截图_20220318203745](https://user-images.githubusercontent.com/5051629/159004366-64675803-b429-4020-b033-d81f1eb26f69.jpg)
l

**Comment by dgatf** [comment]
See now, the pressure, altitude and speed values seems to be correct.

250000bps are correct if you have disabled GPS. If GPS is disabled Jeti uses the arduino UART at pins Rx&Tx (which is shared with the usb, if there is one). Indeed it should be switching from 125000 and 250000 every 5 seconds. If you have GPS disabled in config.h you have to connect Jeti to Rx and Tx pins. Also debug uses Rx&Tx and that's why you need to select 250000

Please now disable DEBUG_MS5611, enable GPS in config.h and connect Jeti to pins 7&12, as usual. It should work

**Comment by ahfynjj** [comment]
I enabled GPS at 115200 bit rate, and it seems normal to see the serial monitor, then I turned off the DEBUG MS5611, connected Jeti to pins 7&12, the problem persists

![微信截图_20220318214751](https://user-images.githubusercontent.com/5051629/159014856-6d6e27f8-8b72-4984-88d0-878597e8bd4a.jpg)

**Comment by ahfynjj** [comment]
Abnormal data was observed, as shown in the figure:
Also, when I tried to blow a 100°C temperature to the 5611 with a heat gun, I didn't see the temperature reading of the sensor in the serial monitor rise, but there was a -2° drop, which is strange
![微信截图_20220318222134](https://user-images.githubusercontent.com/5051629/159020808-31bf95bf-c7c5-4479-b2c9-198063bf8cfd.jpg)
![微信截图_20220318222150](https://user-images.githubusercontent.com/5051629/159020815-6a3f4efc-09eb-4d8a-a5eb-1d2ae572c2db.jpg)
![f319fbadea21fb73cc8d2b85eea0231](https://user-images.githubusercontent.com/5051629/159020945-00384f05-624e-4774-b6a7-644e10df53c6.jpg)
.

**Comment by dgatf** [comment]
To debug MS5611, keep GPS enabled at 9600 in config.h. With a serial monitor at 9600 you'll see the output for MS5611. If you disable GPS, serial monitor will be switching between 125000 and 250000 due to Jeti. Also you will see some garbage characters when in 125000

Regarding the wrong sensor values please download and flash the updated code as there was some issues when converting the raw sensor values

**Comment by ahfynjj** [comment]
Thanks, I downloaded it and saw that the temperature is normal, the Altitude and Vario are still having issues.
At the same time, I also have a FRSKY X20S. I tried to use RX_SMARTPORT, flashed the sensor and connected the GR6 receiver. The data of 5611 displayed on the X20S is normal.
This seems to be a problem with JETI's data processing.

**Comment by dgatf** [comment]
> Altitude and Vario are still having issues

Which issues? There is no additional processing for Jeti

**Comment by ahfynjj** [comment]
https://youtu.be/EgHonEp0JSk
I recorded a video so it will be clearer

**Comment by ahfynjj** [comment]
In order to rule out the problem of 328p, I used teensylc, and connected the iic interface through two wires, and connected GND, the result is the same.
https://youtube.com/shorts/w3mQs1a8D0U?feature=share

**Comment by dgatf** [comment]
Please post the debug for DEBUG_MS5611

**Comment by dgatf** [comment]
It seems an issue of negative numbers with Jeti. I've changed handling of negative numbers for Jeti. Please try the updated code

**Comment by ahfynjj** [comment]
Video of debug for DEBUG_MS5611
https://youtube.com/shorts/aJxN-QgIywY?feature=share

**Comment by ahfynjj** [comment]
I downloaded the latest one and the problem persists

**Comment by dgatf** [comment]
It seems that Jeti uses two complement for negative numbers.

Please try updated code. Should work now.

**Comment by ahfynjj** [comment]
After 10 minutes of testing, 5611 works fine, thank you very much.

**Comment by dgatf** [comment]
Still it was needed to fix number of decimals for negative numbers. Please download updated code.
